#:schema node_modules/wrangler/config-schema.json
name = "ecommerce-store-v2"
main = ".open-next/worker.js"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ecommerce-db"
database_id = "c9359eb2-a5dc-4eff-98f9-bac8118cb3dd"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "ecommerce-store-assets"

[vars]
NEXT_PUBLIC_APP_URL = "https://ecommerce-store-v2.zia291930.workers.dev"
SESSION_SECRET = "d6a39f5011387e0657e7a515cc23681312c5c3c6a83eec464660ca00d935fd7c"
JWT_SECRET = "d6a39f5011387e0657e7a515cc23681312c5c3c6a83eec464660ca00d935fd7c"
ADMIN_SECRET = "admin_secret_key_store_stage2"
ADMIN_EMAIL = "admin@apexstore.com"
