#:schema node_modules/wrangler/config-schema.json
name = "ecommerce-store-perf-test"
main = ".open-next/worker.js"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ecommerce-perf-db"
database_id = "3a60804b-1009-4451-972b-87cec6d46bcb"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "ecommerce-perf-assets"

[vars]
NEXT_PUBLIC_APP_URL = "https://ecommerce-store-perf-test.zia291930.workers.dev"
SESSION_SECRET = "8b051f18ed04fdbfc3aa401da65480ff4cb3b96a5e2082390693b2368a3f06e8"
JWT_SECRET = "8b051f18ed04fdbfc3aa401da65480ff4cb3b96a5e2082390693b2368a3f06e8"
ADMIN_SECRET = "admin_perf_test_secret_2026"
ADMIN_EMAIL = "admin@apexstore.com"
