INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_whatsapp-order', 'whatsapp-order', '1.0.0', 'WhatsApp Order & Chat', 'Enable direct WhatsApp ordering on product pages and a floating customer support chat widget.', 'Nasrify', 'https://nasrify.com', '/icons/whatsapp-order.svg', 'sales', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"whatsapp-order","name":"WhatsApp Order & Chat","version":"1.0.0","description":"Enable direct WhatsApp ordering on product pages and a floating customer support chat widget.","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","read:settings"],"extensionPoints":["storefront.floating","storefront.product.below","storefront.cart.below","storefront.checkout.below","admin.dashboard.widget"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":["app_whatsapp_clicks"],"settingsSchema":{"phoneNumber":{"type":"string","default":"","label":"WhatsApp Phone Number (with country code, e.g. 15551234567)"},"enableFloating":{"type":"boolean","default":true,"label":"Enable Floating WhatsApp Button"},"enableProductButton":{"type":"boolean","default":true,"label":"Enable ''Order on WhatsApp'' on Product Pages"},"floatingMessage":{"type":"string","default":"Hello! I am browsing your store and have a question.","label":"Default Floating Chat Message"},"productMessage":{"type":"string","default":"Hello! I would like to order: {product_name} ({product_url}).","label":"Product Order Message Template"},"buttonText":{"type":"string","default":"Order on WhatsApp","label":"Product Button Text"}},"changelog":"1.0.0 — Initial release"}', '1.0.0 — Initial release', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_whatsapp-order_1_0_0', 'listing_whatsapp-order', '1.0.0', 1789869533519, '{"id":"whatsapp-order","name":"WhatsApp Order & Chat","version":"1.0.0","description":"Enable direct WhatsApp ordering on product pages and a floating customer support chat widget.","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","read:settings"],"extensionPoints":["storefront.floating","storefront.product.below","storefront.cart.below","storefront.checkout.below","admin.dashboard.widget"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":["app_whatsapp_clicks"],"settingsSchema":{"phoneNumber":{"type":"string","default":"","label":"WhatsApp Phone Number (with country code, e.g. 15551234567)"},"enableFloating":{"type":"boolean","default":true,"label":"Enable Floating WhatsApp Button"},"enableProductButton":{"type":"boolean","default":true,"label":"Enable ''Order on WhatsApp'' on Product Pages"},"floatingMessage":{"type":"string","default":"Hello! I am browsing your store and have a question.","label":"Default Floating Chat Message"},"productMessage":{"type":"string","default":"Hello! I would like to order: {product_name} ({product_url}).","label":"Product Order Message Template"},"buttonText":{"type":"string","default":"Order on WhatsApp","label":"Product Button Text"}},"changelog":"1.0.0 — Initial release"}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_reviews', 'reviews', '1.0.0', 'Reviews & Ratings', 'Let customers leave star ratings and written reviews on products', 'Nasrify', 'https://nasrify.com', '/icons/reviews.svg', 'sales', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"reviews","name":"Reviews & Ratings","version":"1.0.0","description":"Let customers leave star ratings and written reviews on products","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","read:orders","read:customers","read:media"],"extensionPoints":["storefront.product.below","admin.dashboard.widget"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":["reviews","review_images"],"settingsSchema":{"autoApprove":{"type":"boolean","default":false,"label":"Auto-approve new reviews"},"requirePurchase":{"type":"boolean","default":false,"label":"Only verified buyers can review"},"allowImages":{"type":"boolean","default":true,"label":"Allow image uploads"}},"changelog":"1.0.0 — Initial release"}', '1.0.0 — Initial release', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_reviews_1_0_0', 'listing_reviews', '1.0.0', 1789869533519, '{"id":"reviews","name":"Reviews & Ratings","version":"1.0.0","description":"Let customers leave star ratings and written reviews on products","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","read:orders","read:customers","read:media"],"extensionPoints":["storefront.product.below","admin.dashboard.widget"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":["reviews","review_images"],"settingsSchema":{"autoApprove":{"type":"boolean","default":false,"label":"Auto-approve new reviews"},"requirePurchase":{"type":"boolean","default":false,"label":"Only verified buyers can review"},"allowImages":{"type":"boolean","default":true,"label":"Allow image uploads"}},"changelog":"1.0.0 — Initial release"}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_bundles', 'bundles', '1.0.0', 'Product Bundles', 'Package multiple products together into high-converting discounted bundle kits.', 'Nasrify', 'https://nasrify.com', '/icons/bundles.svg', 'sales', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"bundles","name":"Product Bundles","version":"1.0.0","description":"Package multiple products together into high-converting discounted bundle kits.","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","write:products","read:media","read:orders"],"extensionPoints":["storefront.homepage.section","storefront.product.below","storefront.cart.below","admin.dashboard.widget"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":["product_bundles","bundle_items"],"settingsSchema":{"enableHomepageSection":{"type":"boolean","default":true,"label":"Enable homepage featured bundles section"},"enableProductCrossSell":{"type":"boolean","default":true,"label":"Enable product detail cross-sell widgets"},"enableCartDiscount":{"type":"boolean","default":true,"label":"Enable bundle pricing & savings discount in cart"},"bundleBadgeText":{"type":"string","default":"Save more with bundle","label":"Bundle badge display text"},"maxBundlesPerSection":{"type":"number","default":4,"label":"Maximum bundles shown per section","description":"Limits the number of bundle cards rendered in showcase sections (1-8)"}},"changelog":"1.0.0 — Initial release as modular app"}', '1.0.0 — Initial release as modular app', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_bundles_1_0_0', 'listing_bundles', '1.0.0', 1789869533519, '{"id":"bundles","name":"Product Bundles","version":"1.0.0","description":"Package multiple products together into high-converting discounted bundle kits.","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","write:products","read:media","read:orders"],"extensionPoints":["storefront.homepage.section","storefront.product.below","storefront.cart.below","admin.dashboard.widget"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":["product_bundles","bundle_items"],"settingsSchema":{"enableHomepageSection":{"type":"boolean","default":true,"label":"Enable homepage featured bundles section"},"enableProductCrossSell":{"type":"boolean","default":true,"label":"Enable product detail cross-sell widgets"},"enableCartDiscount":{"type":"boolean","default":true,"label":"Enable bundle pricing & savings discount in cart"},"bundleBadgeText":{"type":"string","default":"Save more with bundle","label":"Bundle badge display text"},"maxBundlesPerSection":{"type":"number","default":4,"label":"Maximum bundles shown per section","description":"Limits the number of bundle cards rendered in showcase sections (1-8)"}},"changelog":"1.0.0 — Initial release as modular app"}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_order-tracking', 'order-tracking', '1.0.0', 'Order Tracking', 'Live shipment tracking timeline, courier information, and customer order status progression updates.', 'Nasrify Core', 'https://nasrify.com', '/icons/order-tracking.svg', 'operations', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"order-tracking","name":"Order Tracking","version":"1.0.0","description":"Live shipment tracking timeline, courier information, and customer order status progression updates.","author":"Nasrify Core","authorUrl":"https://nasrify.com","icon":"icon.svg","pricing":"free","category":"operations","permissions":["read:orders","write:orders","read:customers","send:notifications"],"extensionPoints":["storefront.account.menu","admin.order.detail.below"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"settingsSchema":{"enablePublicTracking":{"type":"boolean","default":true,"label":"Enable Public Tracking","description":"Allow customers to track order progress on /track-order without requiring an account login"},"enableAutoNotifications":{"type":"boolean","default":true,"label":"Auto Status Notifications","description":"Automatically send notifications to customers when fulfillment status changes"},"showCourierField":{"type":"boolean","default":true,"label":"Show Courier Details","description":"Display courier name and tracking code in the shipment progress timeline"},"showTimeline":{"type":"boolean","default":true,"label":"Show Visual Timeline","description":"Display the visual step-by-step progress timeline on the tracking page"},"timelineStages":{"type":"string","default":"Pending,Confirmed,Packed,Shipped,Out for Delivery,Delivered","label":"Timeline Stages","description":"Comma-separated list of fulfillment stages displayed on customer tracking timelines"},"estimatedDeliveryDays":{"type":"number","default":5,"min":1,"max":30,"label":"Default Estimated Delivery Days","description":"Default delivery timeframe (in days) calculated for new orders"}},"databaseTables":[]}', '1.0.0 - Official Release', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_order-tracking_1_0_0', 'listing_order-tracking', '1.0.0', 1789869533519, '{"id":"order-tracking","name":"Order Tracking","version":"1.0.0","description":"Live shipment tracking timeline, courier information, and customer order status progression updates.","author":"Nasrify Core","authorUrl":"https://nasrify.com","icon":"icon.svg","pricing":"free","category":"operations","permissions":["read:orders","write:orders","read:customers","send:notifications"],"extensionPoints":["storefront.account.menu","admin.order.detail.below"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"settingsSchema":{"enablePublicTracking":{"type":"boolean","default":true,"label":"Enable Public Tracking","description":"Allow customers to track order progress on /track-order without requiring an account login"},"enableAutoNotifications":{"type":"boolean","default":true,"label":"Auto Status Notifications","description":"Automatically send notifications to customers when fulfillment status changes"},"showCourierField":{"type":"boolean","default":true,"label":"Show Courier Details","description":"Display courier name and tracking code in the shipment progress timeline"},"showTimeline":{"type":"boolean","default":true,"label":"Show Visual Timeline","description":"Display the visual step-by-step progress timeline on the tracking page"},"timelineStages":{"type":"string","default":"Pending,Confirmed,Packed,Shipped,Out for Delivery,Delivered","label":"Timeline Stages","description":"Comma-separated list of fulfillment stages displayed on customer tracking timelines"},"estimatedDeliveryDays":{"type":"number","default":5,"min":1,"max":30,"label":"Default Estimated Delivery Days","description":"Default delivery timeframe (in days) calculated for new orders"}},"databaseTables":[]}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_broadcast', 'broadcast', '1.0.0', 'Broadcast Notifications', 'Create storewide promotional announcements, targeted alerts, and modal popups with engagement analytics.', 'Nasrify Core', 'https://nasrify.com', '/icons/broadcast.svg', 'marketing', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"broadcast","name":"Broadcast Notifications","version":"1.0.0","description":"Create storewide promotional announcements, targeted alerts, and modal popups with engagement analytics.","author":"Nasrify Core","authorUrl":"https://nasrify.com","icon":"icon.svg","pricing":"free","category":"marketing","permissions":["read:customers","read:settings"],"extensionPoints":["storefront.floating","admin.dashboard.widget"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"settingsSchema":{"enablePopup":{"type":"boolean","default":true,"label":"Enable Broadcast Popup","description":"Display active broadcast modal popup to visitors on storefront load"},"popupPosition":{"type":"select","default":"top","options":["top","center","bottom"],"label":"Popup Position","description":"Screen positioning for the broadcast announcement modal"},"popupDelaySeconds":{"type":"number","default":3,"min":0,"max":30,"label":"Popup Delay (Seconds)","description":"Number of seconds to wait before displaying broadcast popup"},"showOncePerCustomer":{"type":"boolean","default":true,"label":"Show Once Per Visitor","description":"Do not show the same broadcast again once dismissed or viewed by the visitor"},"enableExpiryDate":{"type":"boolean","default":true,"label":"Enable Auto-Expiry","description":"Automatically hide broadcasts that have exceeded their scheduled expiration date"},"maxActiveBroadcasts":{"type":"number","default":1,"min":1,"max":5,"label":"Max Active Broadcasts","description":"Maximum number of simultaneous active broadcast campaigns displayed"}},"databaseTables":["broadcasts","broadcast_views"]}', '1.0.0 - Official Release', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_broadcast_1_0_0', 'listing_broadcast', '1.0.0', 1789869533519, '{"id":"broadcast","name":"Broadcast Notifications","version":"1.0.0","description":"Create storewide promotional announcements, targeted alerts, and modal popups with engagement analytics.","author":"Nasrify Core","authorUrl":"https://nasrify.com","icon":"icon.svg","pricing":"free","category":"marketing","permissions":["read:customers","read:settings"],"extensionPoints":["storefront.floating","admin.dashboard.widget"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"settingsSchema":{"enablePopup":{"type":"boolean","default":true,"label":"Enable Broadcast Popup","description":"Display active broadcast modal popup to visitors on storefront load"},"popupPosition":{"type":"select","default":"top","options":["top","center","bottom"],"label":"Popup Position","description":"Screen positioning for the broadcast announcement modal"},"popupDelaySeconds":{"type":"number","default":3,"min":0,"max":30,"label":"Popup Delay (Seconds)","description":"Number of seconds to wait before displaying broadcast popup"},"showOncePerCustomer":{"type":"boolean","default":true,"label":"Show Once Per Visitor","description":"Do not show the same broadcast again once dismissed or viewed by the visitor"},"enableExpiryDate":{"type":"boolean","default":true,"label":"Enable Auto-Expiry","description":"Automatically hide broadcasts that have exceeded their scheduled expiration date"},"maxActiveBroadcasts":{"type":"number","default":1,"min":1,"max":5,"label":"Max Active Broadcasts","description":"Maximum number of simultaneous active broadcast campaigns displayed"}},"databaseTables":["broadcasts","broadcast_views"]}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_trust-badges', 'trust-badges', '1.0.0', 'Trust Badges', 'Showcase trust seals, security guarantees, and accepted payment method icons across product, cart, and checkout pages.', 'Nasrify Partner', 'https://nasrify.com', '/icons/trust-badges.svg', 'marketing', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"trust-badges","name":"Trust Badges","version":"1.0.0","description":"Showcase trust seals, security guarantees, and accepted payment method icons across product, cart, and checkout pages.","author":"Nasrify Partner","authorUrl":"https://nasrify.com","icon":"icon.svg","pricing":"free","category":"marketing","permissions":["read:products","read:media","read:settings"],"extensionPoints":["storefront.product.below","storefront.cart.below","storefront.checkout.below","admin.dashboard.widget"],"databaseTables":["trust_badges","payment_icons"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"settingsSchema":{"showOnProductPage":{"type":"boolean","default":true,"label":"Show on Product Page","description":"Display trust badges beneath the product purchase actions"},"showOnCartPage":{"type":"boolean","default":true,"label":"Show on Cart Page","description":"Display trust badges and payment icons on the shopping cart page"},"showOnCheckoutPage":{"type":"boolean","default":true,"label":"Show on Checkout Page","description":"Display trust badges and payment security icons during checkout"},"showPaymentIcons":{"type":"boolean","default":true,"label":"Show Payment Icons","description":"Display accepted payment method icons (Visa, Mastercard, etc.)"},"badgeAlignment":{"type":"select","options":["left","center","right"],"default":"center","label":"Badge Alignment","description":"Horizontal alignment of badges within their containers"},"badgeSize":{"type":"select","options":["sm","md","lg"],"default":"md","label":"Badge Size","description":"Display sizing for trust badges"}}}', '1.0.0 - Official Release', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_trust-badges_1_0_0', 'listing_trust-badges', '1.0.0', 1789869533519, '{"id":"trust-badges","name":"Trust Badges","version":"1.0.0","description":"Showcase trust seals, security guarantees, and accepted payment method icons across product, cart, and checkout pages.","author":"Nasrify Partner","authorUrl":"https://nasrify.com","icon":"icon.svg","pricing":"free","category":"marketing","permissions":["read:products","read:media","read:settings"],"extensionPoints":["storefront.product.below","storefront.cart.below","storefront.checkout.below","admin.dashboard.widget"],"databaseTables":["trust_badges","payment_icons"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"settingsSchema":{"showOnProductPage":{"type":"boolean","default":true,"label":"Show on Product Page","description":"Display trust badges beneath the product purchase actions"},"showOnCartPage":{"type":"boolean","default":true,"label":"Show on Cart Page","description":"Display trust badges and payment icons on the shopping cart page"},"showOnCheckoutPage":{"type":"boolean","default":true,"label":"Show on Checkout Page","description":"Display trust badges and payment security icons during checkout"},"showPaymentIcons":{"type":"boolean","default":true,"label":"Show Payment Icons","description":"Display accepted payment method icons (Visa, Mastercard, etc.)"},"badgeAlignment":{"type":"select","options":["left","center","right"],"default":"center","label":"Badge Alignment","description":"Horizontal alignment of badges within their containers"},"badgeSize":{"type":"select","options":["sm","md","lg"],"default":"md","label":"Badge Size","description":"Display sizing for trust badges"}}}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_cookie-consent', 'cookie-consent', '1.0.0', 'Cookie Consent', 'GDPR and ePrivacy compliant cookie banner, preferences modal, and third-party script blocking engine.', 'Nasrify Partner', 'https://nasrify.com', '/icons/cookie-consent.svg', 'compliance', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"cookie-consent","name":"Cookie Consent","version":"1.0.0","description":"GDPR and ePrivacy compliant cookie banner, preferences modal, and third-party script blocking engine.","author":"Nasrify Partner","authorUrl":"https://nasrify.com","icon":"icon.svg","pricing":"free","category":"compliance","permissions":["read:settings","write:settings","read:customers"],"extensionPoints":["storefront.floating","admin.dashboard.widget"],"databaseTables":["cookie_consent_settings"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"settingsSchema":{"enabled":{"type":"boolean","default":true,"label":"Enable Cookie Consent","description":"Activate cookie consent banner and script blocker across storefront"},"bannerPosition":{"type":"select","options":["bottom","top"],"default":"bottom","label":"Banner Position","description":"Display banner at the bottom or top of the viewport"},"theme":{"type":"select","options":["light","dark","auto"],"default":"auto","label":"Banner Theme","description":"Color theme for the cookie banner and preferences modal"},"showCustomizeButton":{"type":"boolean","default":true,"label":"Show Customize Button","description":"Allow visitors to inspect and toggle individual cookie categories"},"analyticsCategory":{"type":"boolean","default":true,"label":"Analytics Cookies Category","description":"Offer consent toggle for analytical reporting (Google Analytics, Hotjar)"},"marketingCategory":{"type":"boolean","default":true,"label":"Marketing Cookies Category","description":"Offer consent toggle for marketing pixels (Meta, TikTok)"},"functionalCategory":{"type":"boolean","default":true,"label":"Functional Cookies Category","description":"Offer consent toggle for functional user preferences"},"consentExpiryDays":{"type":"number","default":365,"min":30,"max":730,"label":"Consent Expiry (Days)","description":"Days before prompting returning visitors for renewed consent"},"blockScriptsUntilConsent":{"type":"boolean","default":true,"label":"Block Scripts Until Consent","description":"Prevent third-party tracking scripts from firing until explicit consent is granted"}}}', '1.0.0 - Official Release', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_cookie-consent_1_0_0', 'listing_cookie-consent', '1.0.0', 1789869533519, '{"id":"cookie-consent","name":"Cookie Consent","version":"1.0.0","description":"GDPR and ePrivacy compliant cookie banner, preferences modal, and third-party script blocking engine.","author":"Nasrify Partner","authorUrl":"https://nasrify.com","icon":"icon.svg","pricing":"free","category":"compliance","permissions":["read:settings","write:settings","read:customers"],"extensionPoints":["storefront.floating","admin.dashboard.widget"],"databaseTables":["cookie_consent_settings"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"settingsSchema":{"enabled":{"type":"boolean","default":true,"label":"Enable Cookie Consent","description":"Activate cookie consent banner and script blocker across storefront"},"bannerPosition":{"type":"select","options":["bottom","top"],"default":"bottom","label":"Banner Position","description":"Display banner at the bottom or top of the viewport"},"theme":{"type":"select","options":["light","dark","auto"],"default":"auto","label":"Banner Theme","description":"Color theme for the cookie banner and preferences modal"},"showCustomizeButton":{"type":"boolean","default":true,"label":"Show Customize Button","description":"Allow visitors to inspect and toggle individual cookie categories"},"analyticsCategory":{"type":"boolean","default":true,"label":"Analytics Cookies Category","description":"Offer consent toggle for analytical reporting (Google Analytics, Hotjar)"},"marketingCategory":{"type":"boolean","default":true,"label":"Marketing Cookies Category","description":"Offer consent toggle for marketing pixels (Meta, TikTok)"},"functionalCategory":{"type":"boolean","default":true,"label":"Functional Cookies Category","description":"Offer consent toggle for functional user preferences"},"consentExpiryDays":{"type":"number","default":365,"min":30,"max":730,"label":"Consent Expiry (Days)","description":"Days before prompting returning visitors for renewed consent"},"blockScriptsUntilConsent":{"type":"boolean","default":true,"label":"Block Scripts Until Consent","description":"Prevent third-party tracking scripts from firing until explicit consent is granted"}}}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_wishlist', 'wishlist', '1.0.0', 'Wishlist', 'Let customers save products for later', 'Nasrify', 'https://nasrify.com', '/icons/wishlist.svg', 'sales', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"wishlist","name":"Wishlist","version":"1.0.0","description":"Let customers save products for later","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","read:customers","read:media"],"extensionPoints":["storefront.product.below","storefront.header","storefront.account.menu"],"workerScope":{"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":["customer_wishlist"],"settingsSchema":{"showOnProductCards":{"type":"boolean","default":true,"label":"Show heart icon on product cards"},"showInHeader":{"type":"boolean","default":true,"label":"Show wishlist icon in header"},"requireLogin":{"type":"boolean","default":true,"label":"Require login to save"},"iconPosition":{"type":"select","default":"top-right","options":["top-right","top-left","below-image"],"label":"Heart icon position on product cards"}},"changelog":"1.0.0 — Initial release"}', '1.0.0 — Initial release', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_wishlist_1_0_0', 'listing_wishlist', '1.0.0', 1789869533519, '{"id":"wishlist","name":"Wishlist","version":"1.0.0","description":"Let customers save products for later","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","read:customers","read:media"],"extensionPoints":["storefront.product.below","storefront.header","storefront.account.menu"],"workerScope":{"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":["customer_wishlist"],"settingsSchema":{"showOnProductCards":{"type":"boolean","default":true,"label":"Show heart icon on product cards"},"showInHeader":{"type":"boolean","default":true,"label":"Show wishlist icon in header"},"requireLogin":{"type":"boolean","default":true,"label":"Require login to save"},"iconPosition":{"type":"select","default":"top-right","options":["top-right","top-left","below-image"],"label":"Heart icon position on product cards"}},"changelog":"1.0.0 — Initial release"}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_compare', 'compare', '1.0.0', 'Product Compare', 'Allow shoppers to compare technical specifications, prices, and ratings side-by-side.', 'Nasrify', 'https://nasrify.com', '/icons/compare.svg', 'sales', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"compare","name":"Product Compare","version":"1.0.0","description":"Allow shoppers to compare technical specifications, prices, and ratings side-by-side.","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","read:media"],"extensionPoints":["storefront.product.below","storefront.floating"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":[],"settingsSchema":{"maxProducts":{"type":"number","default":4,"label":"Maximum products to compare","description":"Limit of products that can be compared simultaneously (2-6)"},"showInHeader":{"type":"boolean","default":true,"label":"Show compare icon in header"},"buttonStyle":{"type":"select","default":"icon-text","options":["icon","icon-text"],"label":"Compare button display style"}},"changelog":"1.0.0 — Initial release as modular app"}', '1.0.0 — Initial release as modular app', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_compare_1_0_0', 'listing_compare', '1.0.0', 1789869533519, '{"id":"compare","name":"Product Compare","version":"1.0.0","description":"Allow shoppers to compare technical specifications, prices, and ratings side-by-side.","author":"Nasrify","authorUrl":"","icon":"icon.svg","pricing":"free","category":"sales","permissions":["read:products","read:media"],"extensionPoints":["storefront.product.below","storefront.floating"],"workerScope":{"admin":["admin/"],"storefront":["storefront/"],"shared":["manifest.json","icon.svg","lib/","shared/"]},"databaseTables":[],"settingsSchema":{"maxProducts":{"type":"number","default":4,"label":"Maximum products to compare","description":"Limit of products that can be compared simultaneously (2-6)"},"showInHeader":{"type":"boolean","default":true,"label":"Show compare icon in header"},"buttonStyle":{"type":"select","default":"icon-text","options":["icon","icon-text"],"label":"Compare button display style"}},"changelog":"1.0.0 — Initial release as modular app"}', NULL, 'approved', 'Initial verified release'
  );

INSERT OR REPLACE INTO app_marketplace_listings (
    id, app_id, version, name, description, author, author_url, icon_url, category, pricing, price, status, submitted_by, submitted_at, approved_by, approved_at, rejection_reason, download_url, manifest_json, changelog, created_at, updated_at
  ) VALUES (
    'listing_hello-world', 'hello-world', '1.0.0', 'Hello World', 'Demo app to test the framework', 'Nasrify', 'https://nasrify.com', '/icons/hello-world.svg', 'tools', 'free', 0, 'approved', 'system@nasrify.com', 1789869533519, 'admin@apexstore.com', 1789869533519, NULL, NULL, '{"id":"hello-world","name":"Hello World","version":"1.0.0","description":"Demo app to test the framework","author":"Nasrify","icon":"icon.svg","pricing":"free","category":"tools","permissions":["read:settings"],"extensionPoints":["admin.dashboard.widget","storefront.homepage.section"]}', '1.0.0 - Official Release', 1789869533519, 1789869533519
  );

INSERT OR REPLACE INTO app_marketplace_versions (
    id, listing_id, version, submitted_at, manifest_json, download_url, status, notes
  ) VALUES (
    'version_hello-world_1_0_0', 'listing_hello-world', '1.0.0', 1789869533519, '{"id":"hello-world","name":"Hello World","version":"1.0.0","description":"Demo app to test the framework","author":"Nasrify","icon":"icon.svg","pricing":"free","category":"tools","permissions":["read:settings"],"extensionPoints":["admin.dashboard.widget","storefront.homepage.section"]}', NULL, 'approved', 'Initial verified release'
  );