import { SectionSchema } from '../section-schema';

export const PRICING_TABLE_SCHEMA: SectionSchema = {
  type: 'pricing_table',
  label: 'Pricing & Membership Table',
  category: 'promotional',
  description: 'Clean comparison cards or matrix presenting subscription plans, packages, or tiers.',
  variants: [
    { value: 'classic_3col', label: 'Classic 3-Tier Cards' },
    { value: 'comparison_table', label: 'Detailed Feature Matrix' },
    { value: 'cards_with_toggle', label: 'Interactive Annual / Monthly' },
  ],
  presets: [
    {
      name: 'Default 3-Tier',
      settings: {
        variant: 'classic_3col',
        heading: 'Transparent Pricing Designed for Scale',
        subheading: 'Select the membership tier that fits your bespoke lifestyle needs.',
        columns: 3,
        plans: [
          {
            name: 'Essential',
            price: '$29',
            period: '/mo',
            features: 'Access to curated collection\nComplimentary standard delivery\nStandard email support',
            cta_text: 'Get Started',
            cta_link: '/checkout',
            highlighted: false,
          },
          {
            name: 'Privilege',
            price: '$79',
            period: '/mo',
            features: 'Full catalog VIP access\nPriority express shipping\nConcierge 24/7 personal shopper\nEarly drops preview',
            cta_text: 'Join Privilege',
            cta_link: '/checkout',
            highlighted: true,
          },
          {
            name: 'Atelier Bespoke',
            price: '$199',
            period: '/mo',
            features: 'Custom bespoke garment tailoring\nPrivate studio consultations\nUnlimited complimentary courier returns\nExclusive private events invitations',
            cta_text: 'Contact Atelier',
            cta_link: '/contact',
            highlighted: false,
          },
        ],
      },
    },
  ],
  content: [
    { key: 'heading', type: 'richtext', label: 'Section Heading', default: 'Transparent Pricing Designed for Scale' },
    { key: 'subheading', type: 'richtext', label: 'Subheading', default: 'Select the membership tier that fits your bespoke lifestyle needs.' },
    { key: 'columns', type: 'number', label: 'Columns in Row', default: 3, min: 1, max: 4 },
    {
      key: 'plans',
      type: 'repeater',
      label: 'Pricing Plans',
      itemLabel: 'Plan',
      default: [],
      fields: [
        { key: 'name', type: 'text', label: 'Plan Name', default: 'Pro Plan' },
        { key: 'price', type: 'text', label: 'Price (e.g. $49)', default: '$49' },
        { key: 'period', type: 'text', label: 'Billing Period (e.g. /mo)', default: '/mo' },
        { key: 'features', type: 'richtext', label: 'Features (one per line or HTML)', default: 'Priority Support\nFree Delivery' },
        { key: 'cta_text', type: 'text', label: 'Button Label', default: 'Subscribe Now' },
        { key: 'cta_link', type: 'url', label: 'Button Link', default: '/checkout' },
        { key: 'highlighted', type: 'boolean', label: 'Highlight / Most Popular', default: false },
      ],
    },
  ],
  defaults: {
    variant: 'classic_3col',
    heading: 'Transparent Pricing Designed for Scale',
    subheading: 'Select the membership tier that fits your bespoke lifestyle needs.',
    columns: 3,
    plans: [
      {
        name: 'Essential',
        price: '$29',
        period: '/mo',
        features: 'Access to curated collection\nComplimentary standard delivery\nStandard email support',
        cta_text: 'Get Started',
        cta_link: '/checkout',
        highlighted: false,
      },
      {
        name: 'Privilege',
        price: '$79',
        period: '/mo',
        features: 'Full catalog VIP access\nPriority express shipping\nConcierge 24/7 personal shopper\nEarly drops preview',
        cta_text: 'Join Privilege',
        cta_link: '/checkout',
        highlighted: true,
      },
      {
        name: 'Atelier Bespoke',
        price: '$199',
        period: '/mo',
        features: 'Custom bespoke garment tailoring\nPrivate studio consultations\nUnlimited complimentary courier returns\nExclusive private events invitations',
        cta_text: 'Contact Atelier',
        cta_link: '/contact',
        highlighted: false,
      },
    ],
  },
};
